name: CI Implementation on Alta API Testing Mini Project

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
      - name: Build and Test with Maven
        run: mvn --batch-mode --update-snapshots verify
  test:
    name: TEST API AUTOMATION ALTA SHOP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
      - name: TEST API ALTA SHOP MINI PROJECT
        run: mvn clean verify